src/app/navbar/account/profile/account-profile.html, src/components/widget/select/cdvy-select.directive.js, src/components/widget/select/cdvy-select.html, src/components/widget/select/cdvy-select.styl
=> UD-629: Fixed select widget

src/app/factories/create-factory/config-file-tab/factory-from-file.controller.js, src/app/factories/create-factory/projects-tab/factory-from-project.html, src/app/factories/create-factory/projects-tab/factory-from-project.styl, src/components/api/codenvy-factory.factory.js
=> UD-730: Change background for selection in a projects list

src/app/navbar/account/account.controller.js, src/app/navbar/account/profile/account-profile.controller.js, src/app/navbar/account/profile/account-profile.directive.js, src/app/navbar/account/profile/account-profile.html
=> UD-736: Fixed profile attributes form fields after update

src/app/navbar/account/account.controller.js, src/app/navbar/navbar.controller.js, src/app/navbar/navbar.html, src/components/api/codenvy-profile.factory.js
=> Fixed profile API bugs

src/app/projects/create-project/create-project.controller.js, src/app/projects/create-project/create-project.html, src/app/projects/create-project/github/create-project-github.controller.js, src/app/projects/create-project/samples/create-project-samples.controller.js, src/components/widget/input/cdvy-input.directive.js
=> UD-737: Fixed empty description bug after creating project

src/components/widget/select/cdvy-select.directive.js
=> UD-745: Code clean up

src/components/api/codenvy-analytics.factory.js, src/components/api/codenvy-factory.factory.js
=> UD-756: Fixed request for codenvy analytics

src/components/api/codenvy-analytics.factory.js, src/components/api/codenvy-user.factory.js, src/components/api/codenvy-workspace.factory.js
=> UD-779: Added user-invite event for analytic

src/app/projects/create-project/github/create-project-github.controller.js
=> UD-788: Change authorization token request for github

src/app/projects/create-project/create-project.html, src/components/api/codenvy-project.factory.js
=> UD-788: add type checking and removing project description from untyped

gulp/proxy.js, src/app/admin/admin-config.js, src/app/admin/plugins/plugins-config.js, src/app/admin/plugins/plugins-filter.js, src/app/admin/plugins/plugins.controller.js, src/app/admin/plugins/plugins.html, src/app/admin/plugins/plugins.styl, src/app/colors/codenvy-colors.json, src/app/colors/codenvy-colors.styl, src/app/dashboard/dashboard-config.js, src/app/index.js, src/app/navbar/navbar.controller.js, src/app/navbar/navbar.html, src/components/api/codenvy-admin-plugins.factory.js, src/components/api/codenvy-admin-service.factory.js, src/components/api/codenvy-api.factory.js
Change-Id: Ia96e4708729a1d05de18a56e046e04c91d4dd5fc
=> UD-794 Add support for Che Admin plugins API

src/app/admin/plugins/plugins.html, src/app/admin/plugins/plugins.styl, src/components/widget/link/cdvy-link.styl
Change-Id: Iefb67b0e50183c5853813b7f0808a500119618e2
=> UD-807 Polishing plugins view

src/app/colors/codenvy-colors.json, src/app/colors/codenvy-colors.styl, src/app/index.js, src/app/navbar/navbar.styl
PR related to the new styles for UD
=> Ud 790 new style

src/app/navbar/navbar.controller.js, src/app/onboard/onboard-redirect.factory.js, src/components/ims/ims-artifact.factory.js, src/components/onboarding/onboarding.factory.js
=> UD-801: remove onboarding flow if installation manager is available

src/app/navbar/navbar.html, src/app/navbar/team/team-config.js, src/app/navbar/team/team-members-list.controller.js, src/app/navbar/team/team-members-list.directive.js, src/app/navbar/team/team-members-list.html, src/app/navbar/team/team-members-list.styl, src/app/navbar/team/team.html, src/app/navbar/team/team.styl
=> Code clean up

src/app/dashboard/overview/overview.html, src/app/navbar/navbar.controller.js, src/app/navbar/navbar.html, src/components/ims/ims-artifact.factory.js
=> UD-819: exclude subscription and invoice requests for OnPrem

src/components/widget/input/cdvy-input.directive.js
=> UD-821 fix ng-change for the input widget

src/app/navbar/team/team.controller.js
=> UD-887: fix empty account bug

src/components/api/codenvy-workspace.factory.js
Rename dev-machine to ws-machine
=> IDEX-3882. Rename dev-machine to ws-machine

src/app/navbar/team/team.controller.js, src/app/workspaces/create-workspace/create-workspace-add-member.controller.js, src/components/api/codenvy-user.factory.js, src/components/api/codenvy-user.spec.js, src/components/api/test/codenvy-http-backend.js
Linked PR https://github.com/codenvy/che-core/pull/596
=> IDEX-400 Adopt to changes in user API

src/app/onpremises/admin/administration.html, src/app/onpremises/admin/software/software.html, src/app/onpremises/admin/yoursubscription/yoursubscription.html
=> CDEC-440: hide the 'Usage Data' widget

src/app/dashboard/welcome-back/welcome-back.html, src/app/dashboard/welcome-back/welcome-back.styl, src/components/widget/box/cdvy-box.directive.js
=> UD-946 improve styles for the "What should http://localhost:8080 Load"

src/app/navbar/account/account-update-password.styl, src/app/navbar/account/account.controller.js, src/app/navbar/account/account.html, src/app/navbar/navbar.html, src/app/navbar/navbar.styl, src/app/onpremises/create-user/create-user-config.js, src/app/onpremises/create-user/create-user.controller.js, src/app/onpremises/create-user/create-user.html, src/app/onpremises/create-user/create-user.styl, src/app/onpremises/onpremises-config.js, src/components/api/codenvy-user.factory.js, src/components/api/codenvy-user.spec.js, src/components/api/test/codenvy-http-backend.js
=> CDEC-485: add create user form

bower.json, src/app/workspaces/workspace-details/workspace-details.controller.js, src/app/workspaces/workspace-details/workspace-details.html, src/app/workspaces/workspace-status-indicator/workspace-status-indicator.directive.js, src/app/workspaces/workspace-status-indicator/workspace-status-indicator.html, src/app/workspaces/workspace-status-indicator/workspace-status-indicator.styl, src/app/workspaces/workspaces-config.js, src/components/api/codenvy-workspace.factory.js
=> UD-944: add the ability to stop a workspace from UD

src/components/api/codenvy-factory.factory.js
Also initiate user in constructor as it needs to be resolved before loading the route (so we don't need to wait promise callback)
Change-Id: I696be88969ae384119e709fceb56d20bf8cf0adf
=> UD-1001 Avoid to reset list of factories when there is no more factories

src/app/workspaces/workspace-details/workspace-details.controller.js, src/app/workspaces/workspace-details/workspace-details.html, src/app/workspaces/workspace-details/workspace-details.styl
=> UD-994: add ability to start a workspace from UD

src/app/projects/create-project/create-project.controller.js, src/app/workspaces/create-workspace/select-stack/stack-library/create-project-stack-library-selected-stack.filter.js, src/app/workspaces/create-workspace/select-stack/stack-library/create-project-stack-library.controller.js, src/app/workspaces/create-workspace/select-stack/stack-library/create-project-stack-library.html, src/app/workspaces/create-workspace/select-stack/stack-library/create-project-stack-library.styl, src/app/workspaces/create-workspace/select-stack/stack-library/stack-library-filter/cdvy-stack-library-filter.controller.js, src/app/workspaces/create-workspace/select-stack/stack-library/stack-library-filter/cdvy-stack-library-filter.directive.js, src/app/workspaces/create-workspace/select-stack/stack-library/stack-library-filter/cdvy-stack-library-filter.html, src/app/workspaces/create-workspace/select-stack/stack-library/stack-library-filter/cdvy-stack-library-filter.styl, src/app/workspaces/workspaces-config.js
=> UD-947: add filters for the library of stacks

src/assets/html/che-stack.json
Change-Id: I84134eafe47afa7fb098341ed4a4d731522a447c
=> UD-987 Fix issue of versions being not displayed

src/app/projects/create-project/samples/create-project-samples.controller.js
Change-Id: Ibfc0ef534626d0458e1992bac102ecb8be4df0b3
=> UD-988 only apply changes if templates are selected

gulp/svgfont.js
Change-Id: I716167bacc371773afa6752c5af32a09b2f42be0
=> UD-1033 Use a correct font icon order

src/components/attribute/scroll/che-list-on-scroll-bottom.directive.js
=> UD-1022 add new user API

src/app/workspaces/create-workspace/select-stack/ready-to-go-stacks/ready-to-go-stacks.controller.js
=> UD-1035 fix ready-to-go stack

src/index.html
Change-Id: I0993d12e1e53d5fa0dba4266964da5fbae1703c5
=> Remove unused dependency

src/app/index.styl
Change-Id: I9cf3113acf8fc1d30bb1947e4cfa8adfa9e8a04f
=> UD-1037 fix tooltip

src/app/projects/create-project/create-project.controller.js
Change-Id: Ic8dac3c9c8b1ad3e642e9007a6a92b40ba0a0f1a
=> IDEX-4271 Rework promises to avoid loop and use sequential

src/components/body-injector/che-body-injector-config.js, src/components/body-injector/che-body-injector.service.js, src/components/components-config.js
=> UD-879 add body injector service
